const signals = [
    { 
        id: 'S1', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: true, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S2', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S3', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: true },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S3a', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: true },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S4', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S4a', 
        topPlateActive: true, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S5', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: false, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S6', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S6a', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S7', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: true },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S7a', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: true },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S8', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S8a', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S8b', 
        topPlateActive: true, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S9a', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S10', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: true,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S10a', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S11', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: false },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: true,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S11a', 
        topPlateActive: false, 
        topLigth: { active: true, blinking: true },
        topCenterLigth: { active: false, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S12', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: true,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S12a', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S12b', 
        topPlateActive: true, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: true },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: true,
        centerIconActive: true,
        bottomIconActive: true,
    },
    { 
        id: 'S13', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: false,
        topIconActive: true,
        centerIconActive: false,
        bottomIconActive: false,
    },
    { 
        id: 'S13a', 
        topPlateActive: false, 
        topLigth: { active: false, blinking: false },
        topCenterLigth: { active: true, blinking: false },
        centerLigth: { active: false, blinking: false },
        bottomCenterLigth: { active: true, blinking: false },
        bottomLigth: { active: false, blinking: false },
        bottomPlateActive: true,
        topIconActive: false,
        centerIconActive: false,
        bottomIconActive: false,
    },
];